// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace crmDeveloperTestWeb2.Migrations
{
    [DbContext(typeof(CalendarContext))]
    [Migration("20240816094602_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("crmDeveloperTestWeb2.Models.CalendarDay", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("CalendarDays");
                });
#pragma warning restore 612, 618
        }
    }
}
